name: file_share
description: "A Flutter mobile app for the file-sharing backend."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.0.5

  # Networking
  dio: ^5.4.0

  # Secure local storage
  flutter_secure_storage: ^9.0.0

  # File picking
  file_picker: ^10.2.4

  # Open/download files
  open_filex: ^4.3.2

  # Image caching
  cached_network_image: ^3.2.3

  # Charts for analytics
  fl_chart: ^0.66.0

  # Routing
  go_router: ^14.2.0

  path_provider: ^2.1.1

  share_plus: ^7.2.1 

  # UI helpers
  intl: ^0.19.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2

  permission_handler: ^11.0.1  # Add this
  connectivity_plus: ^5.0.1    # Add this for network check

  device_info_plus: ^10.1.0

  flutter_staggered_animations: ^1.1.1
  syncfusion_flutter_gauges: ^26.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
